### PR TITLE
improve permissions logic

### PR DESCRIPTION
**Pull request by geor-kasapidi**
i'v found camera man saves photos into assets. It means that Photos permission is always required. Also, if user wants to pickup images from gallery, but do not want to use camera, we also have to show gallery controller instead of permission blocker.

### CODE REVIEW

**Comment by geor-kasapidi** [comment]
@onmyway133, @zenangst, please, look at my PRs :)

**Comment by onmyway133** [comment]
@geor-kasapidi Hi, sorry for late response. This goes a bit far from our design, but I like the idea. We will refactor this within the swift 4 transition. Thanks for the PR 🚀

**Comment by geor-kasapidi** [comment]
@onmyway133 thank you!

**Comment by LordOfTheRains** [comment]
is anyone else still getting the camera permission prompts? My project never show the camera tab anymore, even on fresh start, i have all the plist item and pre 2.0 version all shows.  for some reason the check() method never trigger the request anymore. any tips on how to fix that?

**Pull request merged**
