### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Cj370118568**
1、add an property isVideoShow to make Video tab show optional
2、add limit num of photo as @telip007 of pull request “Added image limit”(#14)
3、solve the warning
4、make the Cart method reload(_:image:) public to support the need of editing selected photos
5、add selectedIndex to set the initial index

### CODE REVIEW

**Comment by hyouuu** [comment]
Is this repo still being maintained? I really need this optional video showing option as well!

**Comment by onmyway133** [comment]
@Cj370118568 @hyouuu Hi, we 're in the process of refactoring this `Cart` and `showsVideo` thing. I will keep you posted

**Comment by hyouuu** [comment]
Thanks for the quick reply - I'd suggest also add optional camera, as well as having camera being able to use the original ratio and quality rather than the whole screen ratio which comes with lower image quality

**Comment by onmyway133** [comment]
@Cj370118568 @hyouuu Hi, thanks for contributing. We're in the process of refactoring this, and this is the PR https://github.com/hyperoslo/Gallery/pull/24 which we will use to fix those issues

**Pull request closed without merging**
