### PR TITLE
Podspec update to 2.0.7 and swift 4.2

### PR DESCRIPTION
**Pull request by gali8**
I created a new tag on my fork: 2.0.7
than updated the pod spec file to 2.0.7 and swift 4.2

Plase now merge and update on cocoapods.

### CODE REVIEW

**Comment by Schaefers** [comment]
This is missing the fixes necessary to work with Swift 4.2..

**Comment by sbhmajd** [comment]
@onmyway133 can you check this PR please?

**Comment by onmyway133** [comment]
@gali8 @sbhmajd Hi, thanks for the PR 🚀 I will release new version soon

**Comment by sbhmajd** [comment]
@onmyway133 tyvm.

**Comment by sbhmajd** [comment]
@onmyway133 I did the following:

1- Removed the pod
2- Ran pod install
3- Cleaned project with deleting DerivedData
4- Added the pod on master ( 'https://github.com/hyperoslo/Gallery.git', :branch => 'master' )
5- Ran pod install
6- New Gallery installed with 2.0.7 but swift language version still 4.0 ( when multiple schema )

So, I still have my workaround in pod file:

post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'Gallery'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.2'
                end
            end
        end
    end

Please advice?

**Pull request merged**
