### PR TITLE
RxSwiftExtension in README

### PR DESCRIPTION
**Pull request by Dfmarulanda**
Some little information of how to use Gallery+Rx

### CODE REVIEW

**Comment by onmyway133** [comment]
@Dfmarulanda Hi, maybe you forget to commit the source code files ?

**Comment by Dfmarulanda** [comment]
@onmyway133 it's a single file, so i just added a gist link into the README.

**Comment by onmyway133** [comment]
@Dfmarulanda Hi, I would prefer to have `Rx` as a separate subspec in this repo, as we do with other pods. What do you think?

**Comment by zenangst** [comment]
ping @Dfmarulanda :)

**Comment by onmyway133** [comment]
@Dfmarulanda Hi, after some discussion, we think that the `Rx` would be implementation detail that users need to do for their projects, using either RxSwift, Interstellar, ReactiveCocoa, ... So would rather not link it here. Hope you understand.

**Pull request closed without merging**
