### PR TITLE
Update project to Swift 5.0

### PR DESCRIPTION
**Pull request by vcalfa**
Update project to Swift 5.0 and Xcode 10.2

### CODE REVIEW

**Comment by gali8** [comment]
Please @hyperoslo-services push the last version (Swift 5.0 ready) to CocoaPods and update podspec file.
Thanks.

**Comment by lars-fosaas** [comment]
Thanks for the PR. As the current app developer here who is not very experienced in iOS ill try to update the project on cocoapods. Do you have a guide on how to do that? Sorry for the inconvenience.

**Comment by gali8** [comment]
https://guides.cocoapods.org/ and don’t forget to update the podspec file

**Comment by lars-fosaas** [comment]
Gallery v2.2.1 is published. Please let me know if you are experiencing problems.

**Comment by gali8** [comment]
Ok, it works, build succeded.
I don't know (yet) if there are bugs inside :)

**Pull request merged**
